// export const words = [
//   "about",
//   "account",
//   "across",
//   "addition",
//   "after",
//   "again",
//   "against",
//   "agreement",
//   "almost",
//   "among",
//   "amount",
//   "amusement",
//   "angle",
//   "angry",
//   "animal",
//   "answer",
//   "apparatus",
//   "apple",
//   "approval",
//   "argument",
//   "attack",
//   "attempt",
//   "attention",
//   "authority",
//   "automatic",
//   "awake",
//   "balance",
//   "basin",
//   "basket",
//   "beautiful",
//   "because",
//   "before",
//   "behaviour",
//   "belief",
//   "berry",
//   "between",
//   "birth",
//   "bitter",
//   "black",
//   "blade",
//   "blood",
//   "board",
//   "boiling",
//   "bottle",
//   "brain",
//   "brake",
//   "branch",
//   "brass",
//   "bread",
//   "breath",
//   "brick",
//   "bridge",
//   "bright",
//   "broken",
//   "brother",
//   "brown",
//   "brush",
//   "bucket",
//   "building",
//   "burst",
//   "business",
//   "butter",
//   "button",
//   "camera",
//   "canvas",
//   "carriage",
//   "cause",
//   "certain",
//   "chain",
//   "chalk",
//   "chance",
//   "change",
//   "cheap",
//   "cheese",
//   "chemical",
//   "chest",
//   "chief",
//   "church",
//   "circle",
//   "clean",
//   "clear",
//   "clock",
//   "cloth",
//   "cloud",
//   "collar",
//   "colour",
//   "comfort",
//   "committee",
//   "common",
//   "company",
//   "complete",
//   "complex",
//   "condition",
//   "conscious",
//   "control",
//   "copper",
//   "cotton",
//   "cough",
//   "country",
//   "cover",
//   "crack",
//   "credit",
//   "crime",
//   "cruel",
//   "crush",
//   "current",
//   "curtain",
//   "curve",
//   "cushion",
//   "damage",
//   "danger",
//   "daughter",
//   "death",
//   "decision",
//   "degree",
//   "delicate",
//   "dependent",
//   "design",
//   "desire",
//   "detail",
//   "different",
//   "digestion",
//   "direction",
//   "dirty",
//   "discovery",
//   "disease",
//   "disgust",
//   "distance",
//   "division",
//   "doubt",
//   "drain",
//   "drawer",
//   "dress",
//   "drink",
//   "driving",
//   "early",
//   "earth",
//   "education",
//   "effect",
//   "elastic",
//   "electric",
//   "engine",
//   "enough",
//   "equal",
//   "error",
//   "event",
//   "every",
//   "example",
//   "exchange",
//   "existence",
//   "expansion",
//   "expert",
//   "false",
//   "family",
//   "father",
//   "feather",
//   "feeble",
//   "feeling",
//   "female",
//   "fertile",
//   "fiction",
//   "field",
//   "fight",
//   "finger",
//   "first",
//   "fixed",
//   "flame",
//   "flight",
//   "floor",
//   "flower",
//   "foolish",
//   "force",
//   "forward",
//   "frame",
//   "frequent",
//   "friend",
//   "front",
//   "fruit",
//   "future",
//   "garden",
//   "general",
//   "glass",
//   "glove",
//   "grain",
//   "grass",
//   "great",
//   "green",
//   "group",
//   "growth",
//   "guide",
//   "hammer",
//   "hanging",
//   "happy",
//   "harbour",
//   "harmony",
//   "healthy",
//   "hearing",
//   "heart",
//   "history",
//   "hollow",
//   "horse",
//   "hospital",
//   "house",
//   "humour",
//   "important",
//   "impulse",
//   "increase",
//   "industry",
//   "insect",
//   "insurance",
//   "interest",
//   "invention",
//   "island",
//   "jelly",
//   "jewel",
//   "journey",
//   "judge",
//   "kettle",
//   "knife",
//   "knowledge",
//   "language",
//   "laugh",
//   "learning",
//   "leather",
//   "letter",
//   "level",
//   "library",
//   "light",
//   "limit",
//   "linen",
//   "liquid",
//   "little",
//   "living",
//   "loose",
//   "machine",
//   "manager",
//   "market",
//   "married",
//   "match",
//   "material",
//   "measure",
//   "medical",
//   "meeting",
//   "memory",
//   "metal",
//   "middle",
//   "military",
//   "minute",
//   "mixed",
//   "money",
//   "monkey",
//   "month",
//   "morning",
//   "mother",
//   "motion",
//   "mountain",
//   "mouth",
//   "muscle",
//   "music",
//   "narrow",
//   "nation",
//   "natural",
//   "necessary",
//   "needle",
//   "nerve",
//   "night",
//   "noise",
//   "normal",
//   "north",
//   "number",
//   "offer",
//   "office",
//   "operation",
//   "opinion",
//   "opposite",
//   "orange",
//   "order",
//   "ornament",
//   "other",
//   "owner",
//   "paint",
//   "paper",
//   "parallel",
//   "parcel",
//   "paste",
//   "payment",
//   "peace",
//   "pencil",
//   "person",
//   "physical",
//   "picture",
//   "place",
//   "plane",
//   "plant",
//   "plate",
//   "please",
//   "pleasure",
//   "plough",
//   "pocket",
//   "point",
//   "poison",
//   "polish",
//   "political",
//   "porter",
//   "position",
//   "possible",
//   "potato",
//   "powder",
//   "power",
//   "present",
//   "price",
//   "print",
//   "prison",
//   "private",
//   "probable",
//   "process",
//   "produce",
//   "profit",
//   "property",
//   "prose",
//   "protest",
//   "public",
//   "purpose",
//   "quality",
//   "question",
//   "quick",
//   "quiet",
//   "quite",
//   "range",
//   "reaction",
//   "reading",
//   "ready",
//   "reason",
//   "receipt",
//   "record",
//   "regret",
//   "regular",
//   "relation",
//   "religion",
//   "request",
//   "respect",
//   "reward",
//   "rhythm",
//   "right",
//   "river",
//   "rough",
//   "round",
//   "scale",
//   "school",
//   "science",
//   "scissors",
//   "screw",
//   "second",
//   "secret",
//   "secretary",
//   "selection",
//   "sense",
//   "separate",
//   "serious",
//   "servant",
//   "shade",
//   "shake",
//   "shame",
//   "sharp",
//   "sheep",
//   "shelf",
//   "shirt",
//   "shock",
//   "short",
//   "silver",
//   "simple",
//   "sister",
//   "skirt",
//   "sleep",
//   "slope",
//   "small",
//   "smash",
//   "smell",
//   "smile",
//   "smoke",
//   "smooth",
//   "snake",
//   "sneeze",
//   "society",
//   "solid",
//   "sound",
//   "south",
//   "space",
//   "spade",
//   "special",
//   "sponge",
//   "spoon",
//   "spring",
//   "square",
//   "stage",
//   "stamp",
//   "start",
//   "statement",
//   "station",
//   "steam",
//   "steel",
//   "stick",
//   "sticky",
//   "stiff",
//   "still",
//   "stitch",
//   "stocking",
//   "stomach",
//   "stone",
//   "store",
//   "story",
//   "straight",
//   "strange",
//   "street",
//   "stretch",
//   "strong",
//   "structure",
//   "substance",
//   "sudden",
//   "sugar",
//   "summer",
//   "support",
//   "surprise",
//   "sweet",
//   "system",
//   "table",
//   "taste",
//   "teaching",
//   "tendency",
//   "theory",
//   "there",
//   "thick",
//   "thing",
//   "thought",
//   "thread",
//   "throat",
//   "through",
//   "through",
//   "thumb",
//   "thunder",
//   "ticket",
//   "tight",
//   "tired",
//   "together",
//   "tomorrow",
//   "tongue",
//   "tooth",
//   "touch",
//   "trade",
//   "train",
//   "transport",
//   "trick",
//   "trouble",
//   "trousers",
//   "twist",
//   "umbrella",
//   "under",
//   "value",
//   "verse",
//   "vessel",
//   "violent",
//   "voice",
//   "waiting",
//   "waste",
//   "watch",
//   "water",
//   "weather",
//   "weight",
//   "wheel",
//   "where",
//   "while",
//   "whistle",
//   "white",
//   "window",
//   "winter",
//   "woman",
//   "wound",
//   "writing",
//   "wrong",
//   "yellow",
//   "yesterday",
//   "young"
// ];

export const words = [
    "traffic", "datatype", "attribute", "instantiation", "heuristic", "functor", "devops", "cronjob", "value", "session",
    "console", "stylesheet", "polyfill", "benchmark", "bandwidth", "controller", "fragment", "grid", "return", "swap",
    "await", "software", "feature", "truthy", "workaround", "platform", "frontend", "programmer", "stub", "integration",
    "allocation", "driver", "window", "manifest", "viewport", "documentation", "forking", "macro", "workflow", "contract",
    "object", "core", "model", "matrix", "symbol", "infinite", "boundary", "public", "semaphore", "delegation",
    "number", "complexity", "shutdown", "javascript", "timer", "testing", "modulus", "static", "extension", "cluster",
    "breakpoint", "gigabyte", "invocation", "component", "weight", "coverage", "validation", "velocity", "property", "topology",
    "multiplication", "edgecase", "native", "middleware", "floating", "infrastructure", "collection", "table", "traversal", "entity",
    "selection", "xml", "efficiency", "queue", "numeric", "initializer", "site", "framework", "localscope", "casting",
    "global", "wildcard", "linker", "pagination", "inheritance", "cleanup", "folder", "splat", "linkedlist", "foreach",
    "responsiveness", "override", "pseudo", "digest", "infix", "wrapper", "hierarchy", "webhook", "separation", "inference",
    "streaming", "position", "stream", "padding", "unicode", "union", "development", "routing", "reserved", "context",
    "bytecode", "datamining", "division", "vertex", "version", "circuit", "operand", "objective", "raster", "secret",
    "host", "sideeffect", "anonymous", "debugger", "unsigned", "transaction", "verification", "zindex", "unit", "preprocessor",
    "double", "tree", "aggregate", "syntax", "rest", "evaluation", "reverse", "cursor", "key", "stacktrace",
    "web", "subscription", "network", "eager", "sequence", "secure", "abstraction", "localhost", "rendering", "assert",
    "status", "monad", "leak", "hash", "centralized", "hashcode", "unpacking", "configuration", "regular", "closure",
    "segment", "dependency", "deque", "record", "encapsulation", "task", "search", "polymorphism", "text", "fiber",
    "library", "switch", "specification", "priority", "scalar", "promise", "decryption", "higherorder", "gateway", "subclass",
    "maintenance", "assignment", "globalscope", "visual", "alpha", "cohesion", "channel", "throw", "clone", "throttle",
    "logic", "scope", "runtime", "hardcoded", "integrity", "shell", "foreignkey", "deserialization", "reboot", "header",
    "row", "parentheses", "expression", "conversion", "utility", "precision", "microservice", "serialization", "patch", "range",
    "predicate", "transpiler", "webpage", "variable", "lock", "request", "local", "calculation", "basecase", "field",
    "monitor", "enqueue", "page", "retrieval", "capacity", "unshifting", "coordinate", "cookie", "thread", "garbage",
    "unbound", "space", "super", "target", "graph", "register", "principal", "query", "blocking", "function",
    "parallelism", "run", "synchronization", "yield", "superclass", "zero", "location", "token", "placeholder", "scoping",
    "buffer", "notation", "pooling", "decoupling", "concurrency", "filesystem", "supercomputer", "unmarshalling", "daemon", "response",
    "system", "width", "concatenation", "reuse", "adapter", "factory", "ruby", "order", "processing", "getter",
    "telemetry", "redirect", "memoization", "multiprocessing", "process", "trigger", "scale", "user", "heap", "compiler",
    "reflection", "directory", "database", "backtracking", "type", "mutable", "inline", "repository", "semantics", "domain",
    "portal", "racecondition", "iterator", "hardware", "string", "server", "shortcircuit", "plugin", "idempotent", "boolean",
    "widget", "binarytree", "kernel", "binary", "main", "decorator", "renderpass", "character", "interpreter", "deferred",
    "port", "parsing", "assertion", "letter", "path", "transformation", "logger", "iteration", "internal", "increment",
    "statement", "derivation", "worker", "loose", "mocking", "pointer", "decrement", "processor", "falsy", "theme",
    "machine", "requirements", "dispatch", "scheduler", "optional", "normalization", "bitwise", "agile", "unsafe", "lexical",
    "interleaving", "calibration", "template", "initialization", "shadowing", "hyperlink", "offset", "observable", "environment", "partition",
    "default", "executor", "difference", "performance", "svg", "input", "metadata", "display", "lazy", "reset",
    "url", "node", "loop", "integer", "tokenizer", "logical", "camelcase", "client", "router", "strict",
    "canvas", "memory", "structure", "deterministic", "dictionary", "lambda", "currying", "total", "optimizer", "linting",
    "usage", "hosting", "top", "setter", "automation", "unstable", "merge", "privacy", "support", "associative",
    "profiler", "encryption", "class", "literal", "descriptor", "composition", "read", "instruction", "foreground", "interfluent",
    "message", "thumbnail", "readme", "comment", "insertion", "assembler", "module", "overflow", "threshold", "command",
    "variance", "structural", "scrum", "docking", "exception", "store", "event", "resolution", "receiver", "callback",
    "escape", "interface", "protocol", "stdout", "provider", "compression", "constant", "firewall", "append", "constructor",
    "loader", "finalizer", "join", "designpattern", "tuple", "regression", "extensibility", "size", "guard", "dataset",
    "coupling", "scripting", "equality", "specificity", "debounce", "timestamp", "interrupt", "regex", "fetch", "element",
    "recursion", "singleton", "migration", "minimum", "pattern", "information", "serverless", "architecture", "mask", "option",
    "parallel", "long", "mapping", "scalability", "formula", "enum", "keyframe", "fallback", "prefix", "terminal",
    "distributed", "deprecation", "payload", "storage", "section", "digital", "subtraction", "spreadsheet", "synchronous", "statistics",
    "hexadecimal", "tracking", "identifier", "service", "parameter", "destructive", "virtual", "eventdriven", "signature", "execution"
];

export default function RandomWord() {
  const word = words[Math.floor(Math.random() * words.length)]
  return word;
}